"""LabProjection base protocol — what a projection must implement.

Implementations: SQLite (dev), Hydra (production).
"""
from __future__ import annotations

from typing import Protocol, Any


class LabProjection(Protocol):
    """Base protocol for lab projections.

    Implementations project canonical Moltwork events into queryable stores.
    The event ledger is authoritative. Projections are disposable.
    """

    def record_worker(self, worker_id: str, data: dict) -> None: ...
    def record_version(self, version_id: str, worker_id: str, data: dict) -> None: ...
    def record_run(self, run_id: str, worker_id: str, data: dict) -> None: ...
    def record_artifact(self, artifact_id: str, data: dict) -> None: ...
    def record_verification(self, verification_id: str, data: dict) -> None: ...
    def record_outcome(self, run_id: str, outcome: dict) -> None: ...
    def record_learning(self, proposal_id: str, data: dict) -> None: ...
    def retrieve_brief(self, task_family: str, worker_id: str) -> dict: ...
    def rebuild(self) -> None: ...
