"""LearningProposal — typed proposal for worker improvement.

A proposal is generated by Letta reflection, validated by cg,
and promoted only if held-out evaluation shows improvement.
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from core.hashing import sha256, jcs


class ProposalStatus(str, Enum):
    PROPOSED = "PROPOSED"
    UNDER_TEST = "UNDER_TEST"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"


class ProposalTarget(str, Enum):
    MEMORY = "memory"
    SKILL = "skill"
    PROCESS = "process"


@dataclass
class LearningProposal:
    """Typed proposal for worker improvement."""
    proposal_id: str = ""
    worker_version: str = ""  # current version digest
    target: str = "memory"  # ProposalTarget
    path: str = ""  # e.g. "skills/hackathon-requirements/SKILL.md"
    hypothesis: str = ""
    patch: str = ""  # the actual change content
    source_runs: list[str] = field(default_factory=list)
    expected_effects: list[str] = field(default_factory=list)
    status: str = "PROPOSED"  # ProposalStatus
    created_at: float = field(default_factory=time.time)

    def content_hash(self) -> str:
        d = {
            "worker_version": self.worker_version,
            "target": self.target,
            "path": self.path,
            "hypothesis": self.hypothesis,
            "patch": self.patch,
        }
        return sha256(jcs(d))

    def to_dict(self) -> dict:
        return {
            "proposal_id": self.proposal_id,
            "worker_version": self.worker_version,
            "target": self.target,
            "path": self.path,
            "hypothesis": self.hypothesis,
            "patch": self.patch,
            "source_runs": self.source_runs,
            "expected_effects": self.expected_effects,
            "status": self.status,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "LearningProposal":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})
