from __future__ import annotations
import json
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Protocol
from .records import WorkerExecution
from .hashing import sha256_text


class WorkerRuntime(Protocol):
    def ensure_worker(self, worker_id: str, *, model: str = "", persona: str = "") -> dict: ...
    def execute(self, worker_id: str, task: str, workspace: str, *, timeout: int = 300) -> WorkerExecution: ...


class FakeWorkerRuntime:
    """Fast deterministic runtime for orchestration tests.

    It intentionally has the same result shape as the real Letta service, so
    Campaign/Harbor/Hydra plumbing can be tested without spending an LLM turn.
    """
    def __init__(self, artifact_name: str = "submission.md"):
        self.artifact_name = artifact_name
        self.workers: set[str] = set()
        self.counter = 0

    def ensure_worker(self, worker_id: str, *, model: str = "fake/model", persona: str = "") -> dict:
        self.workers.add(worker_id)
        return {"ok": True, "mapping": {"worker_id": worker_id, "letta_agent_id": f"fake-{worker_id}", "model": model}}

    def execute(self, worker_id: str, task: str, workspace: str, *, timeout: int = 300) -> WorkerExecution:
        if worker_id not in self.workers:
            self.ensure_worker(worker_id)
        self.counter += 1
        root = Path(workspace)
        root.mkdir(parents=True, exist_ok=True)
        out = root / self.artifact_name
        body = (
            f"# Candidate Submission {self.counter}\n\n"
            f"Task digest: {sha256_text(task)[:12]}\n\n"
            "## Requirements\n- concrete implementation\n- evidence\n- tests\n\n"
            "## Architecture\nA reproducible worker run produces a Git artifact, then Harbor grades it.\n\n"
            "## Evidence\nThe output is generated by the deterministic FakeWorkerRuntime fixture.\n"
        )
        out.write_text(body)
        return WorkerExecution(
            ok=True,
            worker_id=worker_id,
            conversation_id=f"fake-conv-{self.counter}",
            session_id=f"fake-session-{self.counter}",
            output_content=body,
            artifact_paths=[str(out)],
            duration_ms=1,
            cost_usd=0.0,
            metadata={"runtime": "fake", "timeout": timeout},
        )


class LettaRuntimeClient:
    """Small HTTP client for mw/services/runtime-letta.

    Python does not duplicate the Letta Agent SDK. The Node service remains the
    sole Agent-SDK integration boundary.
    """
    def __init__(self, base_url: str = "http://127.0.0.1:3000", request_timeout: int = 15):
        self.base_url = base_url.rstrip("/")
        self.request_timeout = request_timeout

    def _json(self, method: str, path: str, body: dict | None = None, timeout: int | None = None) -> dict:
        data = None if body is None else json.dumps(body).encode()
        req = urllib.request.Request(
            self.base_url + path,
            data=data,
            method=method,
            headers={"Content-Type": "application/json"},
        )
        try:
            with urllib.request.urlopen(req, timeout=timeout or self.request_timeout) as r:
                payload = json.loads(r.read().decode() or "{}")
        except urllib.error.HTTPError as e:
            detail = e.read().decode(errors="replace")
            raise RuntimeError(f"runtime-letta HTTP {e.code}: {detail}") from e
        return payload

    def health(self) -> dict:
        return self._json("GET", "/health")

    def ensure_worker(self, worker_id: str, *, model: str = "", persona: str = "") -> dict:
        body = {"worker_id": worker_id}
        if model:
            body["model"] = model
        if persona:
            body["persona"] = persona
        return self._json("POST", "/workers", body)

    def execute(self, worker_id: str, task: str, workspace: str, *, timeout: int = 300) -> WorkerExecution:
        started = time.monotonic()
        payload = self._json(
            "POST",
            f"/workers/{worker_id}/run",
            {"task": task, "workspace": workspace, "timeout": timeout},
            timeout=timeout + 20,
        )
        return WorkerExecution(
            ok=bool(payload.get("ok")),
            worker_id=worker_id,
            conversation_id=payload.get("conversation_id", ""),
            session_id=payload.get("session_id", ""),
            output_content=payload.get("output_content", ""),
            duration_ms=int(payload.get("duration_ms") or ((time.monotonic() - started) * 1000)),
            cost_usd=float(payload.get("cost_usd", 0) or 0),
            tool_calls=list(payload.get("tool_calls", [])),
            tool_results=list(payload.get("tool_results", [])),
            metadata={"runtime": "letta-service", "agent_id": payload.get("agent_id", "")},
        )

    def trajectory(self, worker_id: str, conversation_id: str) -> dict:
        return self._json("GET", f"/workers/{worker_id}/trajectory?conversation_id={conversation_id}")
